# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 28, 13, 5, 23, 188590, tzinfo=utc), verbose_name='date released'),
            preserve_default=False,
        ),
    ]
